// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcMsg.proto

package com.wing.common.rpc.protobuf;

public final class RpcMsgOuterClass {
  private RpcMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wing.common.rpc.protobuf.RpcMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否服务器发起的消息
     * </pre>
     *
     * <code>bool server = 1;</code>
     */
    boolean getServer();

    /**
     * <pre>
     *是否属于同步的消息
     * </pre>
     *
     * <code>bool sync = 2;</code>
     */
    boolean getSync();

    /**
     * <code>int64 seqId = 3;</code>
     */
    long getSeqId();

    /**
     * <code>int64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <code>int32 type = 5;</code>
     */
    int getType();

    /**
     * <code>string content = 6;</code>
     */
    String getContent();
    /**
     * <code>string content = 6;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *与content互斥
     * </pre>
     *
     * <code>bytes array = 7;</code>
     */
    com.google.protobuf.ByteString getArray();

    /**
     * <pre>
     *协议编号
     * </pre>
     *
     * <code>int32 msgType = 8;</code>
     */
    int getMsgType();

    /**
     * <code>int64 roleId = 9;</code>
     */
    long getRoleId();
  }
  /**
   * Protobuf type {@code com.wing.common.rpc.protobuf.RpcMsg}
   */
  public  static final class RpcMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wing.common.rpc.protobuf.RpcMsg)
      RpcMsgOrBuilder {
    // Use RpcMsg.newBuilder() to construct.
    private RpcMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcMsg() {
      server_ = false;
      sync_ = false;
      seqId_ = 0L;
      timestamp_ = 0L;
      type_ = 0;
      content_ = "";
      array_ = com.google.protobuf.ByteString.EMPTY;
      msgType_ = 0;
      roleId_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcMsgOuterClass.internal_static_com_wing_common_rpc_protobuf_RpcMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcMsgOuterClass.internal_static_com_wing_common_rpc_protobuf_RpcMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcMsg.class, Builder.class);
    }

    public static final int SERVER_FIELD_NUMBER = 1;
    private boolean server_;
    /**
     * <pre>
     *是否服务器发起的消息
     * </pre>
     *
     * <code>bool server = 1;</code>
     */
    public boolean getServer() {
      return server_;
    }

    public static final int SYNC_FIELD_NUMBER = 2;
    private boolean sync_;
    /**
     * <pre>
     *是否属于同步的消息
     * </pre>
     *
     * <code>bool sync = 2;</code>
     */
    public boolean getSync() {
      return sync_;
    }

    public static final int SEQID_FIELD_NUMBER = 3;
    private long seqId_;
    /**
     * <code>int64 seqId = 3;</code>
     */
    public long getSeqId() {
      return seqId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>int32 type = 5;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private volatile Object content_;
    /**
     * <code>string content = 6;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARRAY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString array_;
    /**
     * <pre>
     *与content互斥
     * </pre>
     *
     * <code>bytes array = 7;</code>
     */
    public com.google.protobuf.ByteString getArray() {
      return array_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 8;
    private int msgType_;
    /**
     * <pre>
     *协议编号
     * </pre>
     *
     * <code>int32 msgType = 8;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int ROLEID_FIELD_NUMBER = 9;
    private long roleId_;
    /**
     * <code>int64 roleId = 9;</code>
     */
    public long getRoleId() {
      return roleId_;
    }

    public static RpcMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wing.common.rpc.protobuf.RpcMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wing.common.rpc.protobuf.RpcMsg)
        RpcMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcMsgOuterClass.internal_static_com_wing_common_rpc_protobuf_RpcMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcMsgOuterClass.internal_static_com_wing_common_rpc_protobuf_RpcMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcMsg.class, Builder.class);
      }

      // Construct using com.wing.common.rpc.protobuf.RpcMsgOuterClass.RpcMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        server_ = false;

        sync_ = false;

        seqId_ = 0L;

        timestamp_ = 0L;

        type_ = 0;

        content_ = "";

        array_ = com.google.protobuf.ByteString.EMPTY;

        msgType_ = 0;

        roleId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcMsgOuterClass.internal_static_com_wing_common_rpc_protobuf_RpcMsg_descriptor;
      }

      public RpcMsg getDefaultInstanceForType() {
        return RpcMsg.getDefaultInstance();
      }

      public RpcMsg build() {
        RpcMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RpcMsg buildPartial() {
        RpcMsg result = new RpcMsg(this);
        result.server_ = server_;
        result.sync_ = sync_;
        result.seqId_ = seqId_;
        result.timestamp_ = timestamp_;
        result.type_ = type_;
        result.content_ = content_;
        result.array_ = array_;
        result.msgType_ = msgType_;
        result.roleId_ = roleId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      private boolean server_ ;
      /**
       * <pre>
       *是否服务器发起的消息
       * </pre>
       *
       * <code>bool server = 1;</code>
       */
      public boolean getServer() {
        return server_;
      }
      /**
       * <pre>
       *是否服务器发起的消息
       * </pre>
       *
       * <code>bool server = 1;</code>
       */
      public Builder setServer(boolean value) {

        server_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否服务器发起的消息
       * </pre>
       *
       * <code>bool server = 1;</code>
       */
      public Builder clearServer() {

        server_ = false;
        onChanged();
        return this;
      }

      private boolean sync_ ;
      /**
       * <pre>
       *是否属于同步的消息
       * </pre>
       *
       * <code>bool sync = 2;</code>
       */
      public boolean getSync() {
        return sync_;
      }
      /**
       * <pre>
       *是否属于同步的消息
       * </pre>
       *
       * <code>bool sync = 2;</code>
       */
      public Builder setSync(boolean value) {

        sync_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否属于同步的消息
       * </pre>
       *
       * <code>bool sync = 2;</code>
       */
      public Builder clearSync() {

        sync_ = false;
        onChanged();
        return this;
      }

      private long seqId_ ;
      /**
       * <code>int64 seqId = 3;</code>
       */
      public long getSeqId() {
        return seqId_;
      }
      /**
       * <code>int64 seqId = 3;</code>
       */
      public Builder setSeqId(long value) {

        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 seqId = 3;</code>
       */
      public Builder clearSeqId() {

        seqId_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {

        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 5;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 5;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 5;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 6;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 6;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 6;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 6;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 6;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString array_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *与content互斥
       * </pre>
       *
       * <code>bytes array = 7;</code>
       */
      public com.google.protobuf.ByteString getArray() {
        return array_;
      }
      /**
       * <pre>
       *与content互斥
       * </pre>
       *
       * <code>bytes array = 7;</code>
       */
      public Builder setArray(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        array_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *与content互斥
       * </pre>
       *
       * <code>bytes array = 7;</code>
       */
      public Builder clearArray() {

        array_ = getDefaultInstance().getArray();
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *协议编号
       * </pre>
       *
       * <code>int32 msgType = 8;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *协议编号
       * </pre>
       *
       * <code>int32 msgType = 8;</code>
       */
      public Builder setMsgType(int value) {

        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议编号
       * </pre>
       *
       * <code>int32 msgType = 8;</code>
       */
      public Builder clearMsgType() {

        msgType_ = 0;
        onChanged();
        return this;
      }

      private long roleId_ ;
      /**
       * <code>int64 roleId = 9;</code>
       */
      public long getRoleId() {
        return roleId_;
      }
      /**
       * <code>int64 roleId = 9;</code>
       */
      public Builder setRoleId(long value) {

        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 roleId = 9;</code>
       */
      public Builder clearRoleId() {

        roleId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.wing.common.rpc.protobuf.RpcMsg)
    }

    // @@protoc_insertion_point(class_scope:com.wing.common.rpc.protobuf.RpcMsg)
    private static final RpcMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcMsg();
    }

    public static RpcMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcMsg>
        PARSER = new com.google.protobuf.AbstractParser<RpcMsg>() {
      public RpcMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcMsg> getParserForType() {
      return PARSER;
    }

    public RpcMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wing_common_rpc_protobuf_RpcMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wing_common_rpc_protobuf_RpcMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014RpcMsg.proto\022\034com.wing.common.rpc.prot" +
      "obuf\"\227\001\n\006RpcMsg\022\016\n\006server\030\001 \001(\010\022\014\n\004sync\030" +
      "\002 \001(\010\022\r\n\005seqId\030\003 \001(\003\022\021\n\ttimestamp\030\004 \001(\003\022" +
      "\014\n\004type\030\005 \001(\005\022\017\n\007content\030\006 \001(\t\022\r\n\005array\030" +
      "\007 \001(\014\022\017\n\007msgType\030\010 \001(\005\022\016\n\006roleId\030\t \001(\003B\002" +
      "H\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wing_common_rpc_protobuf_RpcMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wing_common_rpc_protobuf_RpcMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wing_common_rpc_protobuf_RpcMsg_descriptor,
        new String[] { "Server", "Sync", "SeqId", "Timestamp", "Type", "Content", "Array", "MsgType", "RoleId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
